services:
  postgres_users:
    image: postgres:15-alpine
    container_name: postgres_users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_vehicles:
    image: postgres:15-alpine
    container_name: postgres_vehicles
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicles_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_vehicles_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    command: npm run dev

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      USER_SERVICE_PORT: 4001
      DATABASE_URL: postgresql://postgres:postgres@postgres_users:5432/users_db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672
      RABBIT_EXCHANGE: user.events
    depends_on:
      postgres_users:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "4001:4001"
    command: sh -c "npx drizzle-kit migrate && npm run dev"
    volumes:
      - ./user-service/src:/app/src
      - ./user-service/drizzle:/app/drizzle
      - ./user-service/drizzle.config.ts:/app/drizzle.config.ts

  vehicle-service:
    build: ./vehicle-service
    container_name: vehicle-service
    environment:
      VEHICLE_SERVICE_PORT: 4002
      DATABASE_URL: postgresql://postgres:postgres@postgres_vehicles:5432/vehicles_db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672
      RABBIT_EXCHANGE: user.events
      RABBIT_QUEUE: vehicle.user.created
    depends_on:
      postgres_vehicles:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "4002:4002"
    command: sh -c "npx drizzle-kit migrate && npm run dev"
    volumes:
      - ./vehicle-service/src:/app/src
      - ./vehicle-service/drizzle:/app/drizzle
      - ./vehicle-service/drizzle.config.ts:/app/drizzle.config.ts

volumes:
  postgres_users_data:
  postgres_vehicles_data:
