#!/bin/sh

set -e

echo "[root] Running pre-commit checks..."

echo "[frontend] Running checks..."
sh frontend/.husky/pre-commit

echo "[user-service] Running checks..."
sh user-service/.husky/pre-commit

echo "[vehicle-service] Running checks..."
sh vehicle-service/.husky/pre-commit

echo "[root] All pre-commit checks passed!"
